name: "Mewmba Create PR"
description: "Commit changes to branch, create PR across repositories"

inputs:
  apiGithubToken:
    description: 'Github Api token'
    required: true
  prTitle:
    description: 'PR Title'
    required: false
    default: ''
  prBody:
    description: 'PR Description'
    required: false
    default: ''
  gitSha:
    # TODO - Figure out if this gets passed in
    description: 'githua.sha'
    required: false
    default: ${{ github.event.pull_request_head.sha || github.sha }}
  githubAssignee:
    description: 'Assignee for the created PRs'
    required: false
    default: 'mewmba'
  githubBranch:
    # TODO - Figure out if this gets passed in
    description: 'github.head_ref'
    required: false
    default: ${{ github.head_ref || github.ref_name }}
  githubRepository:
    description: 'Target repository for this PR'
    required: false
    default: ''
  githubWorkingDirectory:
    description: 'Subfolder repository for this PR'
    required: false
    default: ''
  
outputs:
  # TODO - Show more outputs as needed
  prCreated:
    description: 'Boolean of whether a PR was created'
    value: ${{ steps.create-pr.outputs.pr_created }}
  prNumber:
    description: 'Number of the PR created'
    value: ${{ steps.create-pr.outputs.pr_number }}
  prUrl:
    description: 'URL to PR review'
    value: ${{ steps.create-pr.outputs.pr_url }}

runs:
  using: "composite"
  steps:
    - name: Git Short SHA
      id: git-short-sha
      run: |
        echo "shortsha=$('${{ inputs.gitSha }}'.Substring(0,8))" >> $env:GITHUB_OUTPUT
      shell: pwsh
    - name: Create branch, pr, etc names
      id: create-names
      run: |
        echo "newbranchname=mewmba/${{ inputs.githubBranch }}-${{ steps.git-short-sha.outputs.shortsha }}-generated-protos" >> $env:GITHUB_OUTPUT
        echo "oldbranchname=${{ inputs.githubBranch }}" >> $env:GITHUB_OUTPUT
      shell: pwsh
    - name: Default PR title, body
      id: default-pr
      run: |
        echo "defaultprtitle=Generated from ${{ steps.create-names.outputs.oldbranchname }}-${{ steps.git-short-sha.outputs.shortsha }}" >> $env:GITHUB_OUTPUT
        echo "defaultprbody=:rocket: Generated from ${{ steps.create-names.outputs.oldbranchname }} at commit SHA ${{ inputs.gitSha }}" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Commit changes
      uses: actions-js/push@master
      id: commit-changes
      with:
        author_name: Mewmba
        author_email: mewmba@trinsic.id
        github_token: ${{ inputs.apiGithubToken }}
        message: 'Generated code and changes from branch ${{ steps.create-names.outputs.oldbranchname }}, commit SHA ${{ steps.git-short-sha.outputs.shortsha }}'
        branch: ${{ steps.create-names.outputs.newbranchname }}
        directory: '${{ github.workspace }}/${{ inputs.githubWorkingDirectory }}'
        repository: ${{ inputs.githubRepository }}
        force: true

    - name: Create Pull Request
      id: pull-request
      run: |
        gh pr create --head "${{ steps.create-names.outputs.newbranchname }}" `
                     --base "${{ steps.create-names.outputs.oldbranchname }}" `
                     --title "${{ inputs.prTitle || steps.create-names.defaultprtitle }}" `
                     --repo "${{ inputs.githubRepository }}" `
                     --assignee "${{ inputs.githubAssignee }}" `
                     --body @"
        ${{ inputs.prBody || steps.create-names.defaultprbody }}
        "@
      shell: pwsh
      working-directory: ${{ github.workspace }}/${{ inputs.githubWorkingDirectory }}
      env:
        GH_TOKEN: ${{ inputs.apiGithubToken }}
