name: "Mewmba Create PR"
description: "Commit changes to branch, create PR across repositories"

inputs:
  apiGithubToken:
    description: 'Github Api token'
    required: true
  prTitle:
    description: 'PR Title'
    required: false
    default: ''
  prBody:
    description: 'PR Description'
    required: false
    default: ''
  commitMessage:
    description: 'Git Commit message (extract PR title from first line)'
    required: false
    default: ''
  gitSha:
    description: 'github.sha'
    required: false
    default: ${{ github.event.pull_request_head.sha || github.sha }}
  githubAssignee:
    description: 'Assignee for the created PRs'
    required: false
    default: ${{ github.actor }}
  githubBranch:
    description: 'github.head_ref'
    required: false
    default: ${{ github.head_ref || github.ref_name }}
  githubRepository:
    description: 'Target repository for this PR'
    required: false
    default: ${{ github.repository }}
  githubWorkingDirectory:
    description: 'Subfolder repository for this PR'
    required: false
    default: ''
  
outputs:
  prOperation:
    description: 'The pull request operation performed by the action, `created`, `updated`, or `closed`.'
    value: ${{ steps.create-pr.outputs.pull-request-operation }}
  prNumber:
    description: 'The pull request number.'
    value: ${{ steps.create-pr.outputs.pull-request-number }}
  prUrl:
    description: 'The URL of the pull request.'
    value: ${{ steps.create-pr.outputs.pull-request-url }}

runs:
  using: "composite"
  steps:
    - name: Git Short SHA
      id: git-short-sha
      run: |
        echo "shortsha=$('${{ inputs.gitSha }}'.Substring(0,8))" >> $env:GITHUB_OUTPUT
      shell: pwsh
    - name: Create branch, pr, etc names
      id: create-names
      run: |
        echo "newbranchname=mewmba/${{ inputs.githubBranch }}-${{ steps.git-short-sha.outputs.shortsha }}-generated-protos" >> $env:GITHUB_OUTPUT
        echo "oldbranchname=${{ inputs.githubBranch }}" >> $env:GITHUB_OUTPUT
      shell: pwsh
    - name: Default PR title, body
      id: default-pr
      run: |
        $gitcommit = @'
        ${{ inputs.commitMessage }}
        '@
        $gitlines = $gitcommit.Split("`r`n")
        $gittitle = $gitlines[0]
        $gittitle = $gittitle.Substring(0,[math]::Min($gittitle.Length,64))
        echo "defaultprtitle=Generated from ${{ steps.create-names.outputs.oldbranchname }}-${{ steps.git-short-sha.outputs.shortsha }}" >> $env:GITHUB_OUTPUT
        echo "defaultprbody=:rocket: Generated from ${{ steps.create-names.outputs.oldbranchname }} at commit SHA ${{ inputs.gitSha }}" >> $env:GITHUB_OUTPUT
        echo "commitprtitle=$($gittitle)" >> $env:GITHUB_OUTPUT
        echo "commitprbody=$gitcommit" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ inputs.apiGithubToken }}
        path: ${{ inputs.githubWorkingDirectory }}
        commit-message: 'Generated code and changes from branch ${{ steps.create-names.outputs.oldbranchname }}, commit SHA ${{ steps.git-short-sha.outputs.shortsha }}'
        committer: Mewmba <mewmba@trinsic.id>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: ${{ steps.create-names.outputs.newbranchname }}
        delete-branch: true
        base: ${{ steps.create-names.outputs.oldbranchname }}
        title: ${{ inputs.prTitle || steps.default-pr.outputs.commitprtitle || steps.default-pr.outputs.defaultprtitle }}
        body: ${{ inputs.prBody || steps.default-pr.outputs.commitprbody || steps.default-pr.outputs.defaultprbody }}
        reviewers: ${{ inputs.githubAssignee }}
    - uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ inputs.apiGithubToken }}
        pull-request-number: ${{ steps.create-pr.pull-request-number }}
