name: "Mewmba Create PR"
description: "Commit changes to branch, create PR across repositories"

inputs:
  apiGithubToken:
    description: 'Github Api token'
    required: true
  prTitle:
    description: 'PR Title'
    required: false
    default: ''
  prBody:
    description: 'PR Description'
    required: false
    default: ''
  gitSha:
    # TODO - Figure out if this gets passed in
    description: 'githua.sha'
    required: false
    default: ${{ github.event.pull_request_head.sha || github.sha }}
  githubBranch:
    # TODO - Figure out if this gets passed in
    description: 'github.head_ref'
    required: false
    default: ${{ github.head_ref || github.ref_name }}
  githubRepository:
    description: 'Target repository for this PR'
    required: false
    default: ''
  githubWorkingDirectory:
    description: 'Subfolder repository for this PR'
    required: false
    default: ''
  
outputs:
  # TODO - Show more outputs as needed
  prCreated:
    description: 'Boolean of whether a PR was created'
    value: ${{ steps.create-pr.outputs.pr_created }}
  prNumber:
    description: 'Number of the PR created'
    value: ${{ steps.create-pr.outputs.pr_number }}
  prUrl:
    description: 'URL to PR review'
    value: ${{ steps.create-pr.outputs.pr_url }}

runs:
  using: "composite"
  steps:
    - name: Git Short SHA
      id: git-short-sha
      run: |
        echo "shortsha=$(echo ${{ inputs.gitSha}} | cut -b 0-8)" >> $env:GITHUB_OUTPUT
      shell: pwsh
    - name: Create branch, pr, etc names
      id: create-names
      run: |
        echo "newbranchname=mewmba/${{ inputs.githubBranch }}-${{ steps.git-short-sha.shortsha }}-generated-protos" >> $env:GITHUB_OUTPUT
        echo "oldbranchname=${{ inputs.githubBranch }}" >> $env:GITHUB_OUTPUT
        echo "defaultprtitle=Generated from ${{ steps.create-names.outputs.oldbranchname }}-${{ steps.git-short-sha.shortsha }}" >> $env:GITHUB_OUTPUT
        echo "defaultprbody=:rocket: Generated from ${{ steps.create-names.outputs.oldbranchname }} at commit SHA ${{ inputs.gitSha }}" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      id: commit-changes
      with:
        author_name: Mewmba
        author_email: mewmba@trinsic.id
        message: 'Generated code and changes from branch ${{ steps.create-names.outputs.oldbranchname }}, commit SHA ${{ steps.git-short-sha.shortsha }}'
        new_branch: ${{ steps.create-names.outputs.newbranchname }}
        push: '--force --set-upstream origin ${{ steps.create-names.outputs.newbranchname  }}'
        cwd: ${{ github.workspace }}/${{ inputs.githubWorkingDirectory }}

    # TODO - Can we switch to github API?
    - name: pull-request
      uses: commercetools/pull-request@add-workdir
      id: create-pr
      if: ${{ steps.commit_changes.outputs.committed == 'true' }}
      with:
        source_branch: ${{ steps.create-names.outputs.newbranchname }}
        destination_branch: ${{ steps.create-names.outputs.oldbranchname }}
        pr_title: ${{ inputs.prTitle || steps.create-names.defaultprtitle }}
        pr_body: ${{ inputs.prBody || steps.create-names.defaultprbody }}
        pr_allow_empty: false
        github_token: ${{ inputs.apiGithubToken }}
        working_directory: ${{ github.workspace }}/${{ inputs.githubWorkingDirectory }}
        repository: ${{ inputs.githubRepository }}