name: "Random Mewmba Actions"

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    name: Basic Functionality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        name: Setup Node v16
        with:
          node-version: 16
          cache: 'npm'
      - name: Mewmba Test
        run: |
          npm ci
          npm test
        env:
          GATHER_SPACE_ID: ${{ secrets.GATHER_SPACE_ID }}
          GATHER_MAP_ID: ${{ secrets.GATHER_MAP_ID }}
          GATHER_API_KEY: ${{ secrets.GATHER_API_KEY }}
        shell: pwsh